<a href="https://colab.research.google.com/github/yj4976s-cpu/AI_26/blob/main/%EB%84%98%ED%8C%8C%EC%9D%B4_%EA%B3%B5%EB%B6%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np

In [43]:
print(np.array([1,2,3]))

[1 2 3]


In [44]:
import numpy as np

arr_1 = np.array([1,2,3,4,5]) # 파이썬 리스트를 넘파일 배열로 변환
print(arr_1) # 넘파일 배열 출력

[1 2 3 4 5]


In [45]:
[1,2,3,4,5]*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [46]:
arr_1*2

array([ 2,  4,  6,  8, 10])

In [47]:
import numpy as np

arr_2 = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]]
) # 파이썬 리스트를 ndarray로 변환
print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
import numpy as np
arr_3 = np.array([[[1,2,3],
                  [4,5,6]],
                 [[7,8,9],
                  [10,11,12]]
                 [[13, 14, 15],
                  [16, 17, 18]]])

<>:4: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:4: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/tmp/ipykernel_2479/3180857046.py:4: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [[7,8,9],


TypeError: list indices must be integers or slices, not tuple

In [ ]:
import numpy as np

arr_1 = np.array([1,2,3,4,5])
print(arr_1.dtype)

In [ ]:
import numpy as np

print(np.array([1,2,3]).dtype)

In [ ]:
print(np.array([1,2,3], dtype='int8').dtype)

In [ ]:
print(np.array([1,2,3], dtype='i1').dtype)

In [ ]:
import numpy as np
ndarray_1 = np.array([1,2,3]) # 넘파이 배열
ndarray_2 = np.array([4,5,6])
list_1 = [1,2,3] # 파이썬 리스트
list_2 = [4,5,6]
print(ndarray_1 + ndarray_2) # 넘파이 배열 연산
print(list_1 + list_2)

In [ ]:
result_list = [x+y for x, y in zip(list_1, list_2)]
print(result_list)

In [ ]:
print(ndarray_1*2)
print(list_1*2)

In [ ]:
import numpy as np

a= np.array([2,3,4]) # 넘파이 정수형 배열 생성
print(a) # 넘파이 배열 출력
print(a.dtype) # 넘파이 배열의 데이터 타입 출력
b = np.array([2.1, 3.2, 4.3]) # 넘파이 실수형 배열 생성
print(b) # 넘파이 배열 출력
print(b.dtype)


In [ ]:
c = np.array(('i','j','k')) # 넘파이 문자열 생성
print(c)
print((c.dtype)) # 데이터 타입 확인

In [ ]:
d = np.array((True, True, False)) # 넘파이 논리형 배열 생성
print(d)
print(d.dtype)

In [ ]:
e = np.array(['ab','cd','e'], dtype='<U2') # 문자열 길이를 조절하여 배열 생성
print(e)
print(e.dtype)

In [ ]:
import numpy as np
# a라는 변수에 (3,4) 크기의 넘파이 2차원 배열 생성
a = np.arange(12).reshape(3,4)
print(a)

In [ ]:
print(a.shape) # 배열의 차원과 차원의 크기 반환
print(a.ndim) # 배열의 차원 수 반환
print(a.dtype) # 배열의 데이터 타입 반환
print(a.itemsize) # 배열의 각 요소의 크기를 바이트 단위로 반환
print(a.size) # 배열의 총 요소의 수 반환

In [ ]:
import numpy as np

# 각 학급에 4명의 학생, 각 학생이 3과목의 시험점수를 가지고 있는 배열 생성
# 예시: 3개의 학급, 각 학급에 4명의 학생, 각 학생당 국어, 영어, 수학 점수
scores = np.random.randint(0, 101, size=(3, 4, 3))

# 학급별, 학생별, 과목별 점수를 출력
print("학급별 학생들의 점수 배열 (3차원 배열):")
print(scores)

# 학급, 학생, 과목별로 점수 출력
for class_idx in range(scores.shape[0]):
    for student_idx in range(scores.shape[1]):
        Korean, english, math = scores[class_idx, student_idx]
        print(f"Student {student_idx + 1} - Korean: {Korean}, English: {english}, Math: {math}")

In [ ]:
import numpy as np

# (3,4) 크기의 배열을 생성하여 0으로 채움
print(np.zeros((3,4)))
# (3,4) 크기의 배열을 데이터 타입을 정수로 생성한 후, 0으로 채움
print(np.zeros((3,4), dtype=int))

In [ ]:
# (2,3,4) 크기의 배열을 생성하여 데이터 타입을 정수로 설정한 후, 1로 채움
print(np.ones((2,3,4), dtype=int))

In [ ]:
# (2, 3) 크기의 빈 배열 생성
print(np.empty((2,3)))

In [ ]:
import numpy as np
# 10이상 30 미만 까지 5간격으로 생성
print(np.arange(10, 30, 5))
# 0이상 2 미만까지 0.3 간격으로 생성
print(np.arange(start = 0, stop = 2, step = 0.3))

In [ ]:
# 1이상 10이하까지 값을 가진 크기 10짜리 배열 생성
print(np.linspace(start=1, stop=10, num=10, dtype = int))

In [ ]:
import numpy as np
# a와 b배열 생성하여 출력
a = np.array([10, 20, 30, 40])
b = np.arange(start = 1, stop = 5)
print(a)
print(b)

# 덧셈연산
print(a+b)
# 뺄셈연산
print(a-b)
# 곱셈연산
print(a*b)
# 나눗셈연산
print(a/b)

In [ ]:
# A와 B 배열 생성
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

# A * B : 요소별 곱셈 연산
print(A*B)
# A @ B : 행렬 곱셈 사용
print(A @ B)

In [ ]:
import numpy as np

# A와 B배열 생성
A = np.array([1,2,3,4])
B = np.array([1,1,3,3])
# 비교 연산
print(A > B)
print(A == B)

In [ ]:
import numpy as np

# 두 명의 학생의 시험점수를 배열로 생성합니다.
student1_scores = np.array([85, 90, 78]) # 학생 1의 점수 (국어, 영어, 수학)
student2_scores = np.array([92, 88, 95]) # 학생 2의 점수 (국어. 영어, 수학)

# 두 학생의 점수를 출력합니다.
print("학생 1의 점수:", student1_scores)
print("학생 2의 점수:", student2_scores)

# 두 학생의 총점을 구합니다.
total_scores = student1_scores + student2_scores
print("두 학생의 총점:", total_scores)

# 두 학생의 평균점수를 구합니다.
averge_scores=total_scores/2
print("두 학생의 평균 점수", averge_scores)

# 각 학생의 총점과 평균을 구합니다.
student1_total = np.sum(student1_scores)
student2_total= np.sum(student2_scores)
student1_average = np.mean(student1_scores)
student2_average = np.mean(student2_scores)

print("학생 1의 총점:", student1_total)
print("학생 1의 평균:", student1_average)
print("학생 2의 총점:", student2_total)
print("학생 2의 평균:", student2_average)

In [ ]:
import numpy as np
# A 배열 생성
A = np.array([4, 16, 25])
# 제곱근 함수
print(np.sqrt(A))

In [ ]:
# a 배열 생성 & 출력
# 0부터 8 미만까지 출력하고 (2,4)크기로 재가공하고 제곱하여 출력
a = np.arange(8).reshape(2,4)**2
print(a)

# 모든 요소의 합
print(a.sum())
# 모든 요소 중 평균
print(a.mean())
# 모든 요소 중 최솟값
print(a.min())
# 모든 요소 중 최댓값
print(a.max())
# 모든 요소의 누적합
print(a.cumsum())
# 모든 요소 중 최댓값의 인덱스
print(a.argmax())

In [ ]:
import numpy as np

# 0부터 8미만까지 출력하고 (2,4)크기로 재가공하고 제곱하여 출력
# a = array([[0, 1, 4, 9], [16, 25, 36, 49]])
a = np.arange(8).reshape(2,4)**2

# axis = 0은 열 기준으로 연산
print(a.mean(axis = 0))
# axis = 1은 행 기준으로 연산
print(a.max(axis =1))

In [ ]:
import numpy as np
a =  np.array([0, 1, 2, 3, 4, 5])
print(a)
print(a[0])
print(a[3])

In [ ]:
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b)

# 인덱스가 [1, 0]인, 인덱스가 [1, 2]인 요소 출력
print(b[1, 0])
print(b[1, 2])

In [ ]:
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5])
print(a)

# 인덱스 0 이상 인덱스 3 미만 범위의 요소 출력
print(a[0:3])

In [ ]:
import numpy as np

a = np.arange(12).reshape(3,4)
print(a)

# a > 4 조건을 적용한 논리형 배열 생성
b = a > 4
print(b)

In [ ]:
print(a[b]) # 논리형 배열 b를 사용하여 조건에 맞는 요소를 추출
print(a[b].shape) # 추출한 요소들의 배열모양

In [ ]:
# 논리형 배열인 b를 이용하여 원본 a 배열의 값 변경하기(True인 값의 위치에 변경하기)
a[b] = 1000
print(a)

In [ ]:
import numpy as np
a = np.array(['a', 'b', 'c', 'd', 'e','f', 'g', 'h'])
i = np.array([1, 1, 3, 4])

# 배열 a에서 배열 i에서 지정된 인덱스의 원소들을 출력
print(a[i])
j = np.array([[3,4], [5, 6]])

# 배열 a에서 배열 j에 지정된 인덱스의 원소들을 출력
print(a[j])

In [ ]:
b = np.array(['a','b','c','d'])
k = np.array([3, 2, 1, 0])

# 배열 b에서 배열 k에 지정된 인덱스의 원소들을 재배열
b = b[k]
print(b)

In [ ]:
import numpy as np

# a 배열 생성
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)
print(a.ndim)

In [ ]:
# .reshape : 지정한 차원으로 변경하고 새로운 배열 반환
b= a.reshape(2, 6)
print(b)
print(b.shape)

# 원본 a 배열은 기존의 (3, 4) 형태 유지
print(a)
print(a.shape)

In [49]:
c = a.reshape(-1,3)
print(c)
print(c.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [50]:
import numpy as np
# .resize() : 지정한 차원으로 변경하고 원본 배열 자체를 변경
a = np.arange(12)
a.resize(4,3)
print(a)
print(a.shape)

# 따로 반환하는 값 없음
print(a.resize(4,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
None


In [51]:
import numpy as np
a = np.arange(12).reshape(3,4)

# .rabel() : 1차원 배열로 크기 변경
print(a.ravel())
#.reshape(-1) : 1차원 배열로 크기 변경
print(a.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [52]:
import numpy as np

A = np.arange(12).reshape(2,6)
print(A)

# .T ; [2,6]을 [6,2] 반환으로 전치(transpose) 변환
print(A.T)
print(A.T.shape)

# 만약 전치 형태로 원본 A 배열에 저장하고 싶다면, A배열에 A.T 값을 할당
A = A.T
print(A)
print(A.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
(6, 2)
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
(6, 2)


In [53]:
import numpy as np
# a 배열, b 배열 생성
a = np.array([1,2,3,4]).reshape(2, 2)
b = np.array([5,6,7,8]).reshape(2, 2)

# 수직으로 합치기
print(np.vstack((a, b)))

# 수평으로 합치기
print(np.hstack((a, b)))
#

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [54]:
import numpy as np

# a 배열, b 배열 생성
a = np.arange(12).reshape(2,6)
print(a)

# 수직으로 분할하기
print(np.vsplit(a,2))
# 수평으로 분할하기
print(np.hsplit(a,3))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]
[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]


In [55]:
import numpy as np
# 고객 데이터 배열 생성
customer = np.array([
    [150, 25, 0],
    [200, 30, 0],
    [50, 10, 1],
    [300, 45, 0],
])

print(customer)

[[150  25   0]
 [200  30   0]
 [ 50  10   1]
 [300  45   0]]


In [73]:
# 새로운 고객데이터 배열 생성
new_customer = np.array([
    [120, 20, 0],
    [180, 35, 1],
    [75, 5, 0],
    [160, 25, 0]
])

# 새로운 고객 데이터를 기존 배열에 합치기
combined_data = np.vstack((customer, new_customer))

# 결과 확인
print(combined_data)

[[150  25   0]
 [200  30   0]
 [ 50  10   1]
 [300  45   0]
 [120  20   0]
 [180  35   1]
 [ 75   5   0]
 [160  25   0]]


In [74]:
# 열 단위로 총합 계산
column_sums = combined_data.sum(axis=0)
total_comment_length = column_sums[0]
total_likes = column_sums[1]

# 열 단위로 평균 계산
column_means = combined_data.mean(axis=0)
average_comment_length = column_means[0]
average_likes = column_means[1]

# 결과 확인
print("댓글 길이 총합:", total_comment_length)
print("좋아요 수 총합:", total_likes)
print("댓글 길이 평균:", average_comment_length)
print("좋아요 수 평균:", average_likes)

댓글 길이 총합: 1235
좋아요 수 총합: 195
댓글 길이 평균: 154.375
좋아요 수 평균: 24.375


In [75]:
# 8개의 데이터를 위아래로 4개의 그룹으로 나누어 배열 생성
groups = np.vsplit(combined_data,4)
print(groups)

[array([[150,  25,   0],
       [200,  30,   0]]), array([[ 50,  10,   1],
       [300,  45,   0]]), array([[120,  20,   0],
       [180,  35,   1]]), array([[ 75,   5,   0],
       [160,  25,   0]])]


In [76]:
select_customers = combined_data[[0,2,4], :]

print(select_customers)

[[150  25   0]
 [ 50  10   1]
 [120  20   0]]


In [77]:
transposed_data = combined_data.T
print(transposed_data)

[[150 200  50 300 120 180  75 160]
 [ 25  30  10  45  20  35   5  25]
 [  0   0   1   0   0   1   0   0]]


In [78]:
new_customers = np.zeros((2,3), dtype = int)
print(new_customers)

[[0 0 0]
 [0 0 0]]


In [79]:
## 좋아요 수에 10을 추가
combined_data[:, 1] = combined_data[:, 1] + 10

## 결과 확인
print(combined_data)

[[150  35   0]
 [200  40   0]
 [ 50  20   1]
 [300  55   0]
 [120  30   0]
 [180  45   1]
 [ 75  15   0]
 [160  35   0]]


In [80]:
## 조건에 맞는 고객 데이터 추출
selected_customers = combined_data[(combined_data[:, 0] >= 100) & (combined_data[:, 1] >= 20) & (combined_data[:, 2] == 0)]

## 결과 확인
print(selected_customers)

[[150  35   0]
 [200  40   0]
 [300  55   0]
 [120  30   0]
 [160  35   0]]


In [81]:
# 조건을 만족하는 고객 수 계산
num_selected_customers = selected_customers.shape[0]

# 결과 확인
print("상품을 받을 고객 수:", num_selected_customers)

상품을 받을 고객 수: 5
